version: "3.9"

services:
  api:
    build: .
    container_name: send_money_api
    ports:
      - "8000:8000"
    env_file:
      - .env
    restart: always

  ui:
    build: .
    container_name: send_money_ui
    command: streamlit run ui/app_ui.py --server.port=8501 --server.address=0.0.0.0
    ports:
      - "8501:8501"
    env_file:
      - .env
    depends_on:
      - api
    restart: always